# Se usa cuando falta una plantilla propia. No debe borrarse.
title: Página
icon: page

status:
  draft: true
  unlisted:
    label: Oculta
    text: No aparece en el menú
  listed:
    label: En el menú
    text: Aparece en el menú principal

fields:
  text:
    label: Texto
    type: textarea
    size: huge
